import React from "react";
import { Icon } from "semantic-ui-react";

export const ShareableData = [
  {
    Status: "Shareable Accounts",
    customerID: 1244443,
    customerCategory: "Enterprise",
    customerName: "PT.ABU BAKAR",
    CustomerAddress: "JL Agung Niaga V BI",
    lastProjectName: "Invetory Delivery Performance & Lifecyle",
    salesAssign: "Anjar Wahyudi Laksamana",
    pmoCustomer: "true",
    relatedCustomer: "EAST MODERN LOCATIONS, NORTH MODERN LOCATIONS",
    blacklist: true,
    holdshipment: false,
    createUserID: "Jahal Aja Aw",
    createDate: "08/01/2026",
    modifyUserID: "Jane Copper",
    modifyDate: "11/12/2030",
  },
  {
    Status: "Shareable Accounts",
    customerID: 666666,
    customerCategory: "Enterprise",
    customerName: "PT.ABU Jahal Abu Janda Astagfirullah",
    CustomerAddress: "JL Musi Bah",
    lastProjectName: "Invetory Delivery Performance & Lifecyle",
    salesAssign: "Prabowo Subianto ",
    pmoCustomer: "false",
    relatedCustomer: "EAST MODERN LOCATIONS, NORTH MODERN LOCATIONS",
    blacklist: false,
    holdshipment: true,
    createUserID: "Jahal",
    createDate: "08/01/2026",
    modifyUserID: "Jane Reaper Reaper",
    modifyDate: "01/09/2035",
  },
  {
    Status: "No Name Accounts",
    customerID: 123,
    customerCategory: "Enterprise",
    customerName: "PT.ABU BAKAR",
    CustomerAddress: "JL Agung Niaga V BI",
    blacklist: true,
    holdshipment: false,
    createUserID: "Jahal Aja Aw",
    createDate: "08/01/2026",
    modifyUserID: "Jane Copper",
    modifyDate: "11/12/2030",
  },
  {
    Status: "Name Accounts",
    customerID: 1244443,
    customerCategory: "Enterprise",
    customerName: "PT.ABU BAKAR",
    CustomerAddress: "JL Agung Niaga V BI",
    lastProjectName: "Invetory Delivery Performance & Lifecyle",
    salesName: "Sayang Biarlah",
    pmoCustomer: "true",
    relatedCustomer: "EAST MODERN LOCATIONS, NORTH MODERN LOCATIONS",
    blacklist: true,
    holdshipment: false,
    createUserID: "Jahal Aja Aw",
    createDate: "08/01/2026",
    modifyUserID: "Jane Copper",
    modifyDate: "11/12/2030",
  },
];
